/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'Today': RouteRecordInfo<
      'Today',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Events': RouteRecordInfo<
      'Events',
      '/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LifeLog': RouteRecordInfo<
      'LifeLog',
      '/lifelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PartnerDetail': RouteRecordInfo<
      'PartnerDetail',
      '/partner/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ProfileEdit': RouteRecordInfo<
      'ProfileEdit',
      '/profile/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Settings': RouteRecordInfo<
      'Settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Share': RouteRecordInfo<
      'Share',
      '/share',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'MediaDetail': RouteRecordInfo<
      'MediaDetail',
      '/share/media/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'Todos': RouteRecordInfo<
      'Todos',
      '/todos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Today'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/events/index.vue': {
      routes:
        | 'Events'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forgot-password/index.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/lifelog/index.vue': {
      routes:
        | 'LifeLog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/partner/detail.vue': {
      routes:
        | 'PartnerDetail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/edit.vue': {
      routes:
        | 'ProfileEdit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | 'Register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'Settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/share/index.vue': {
      routes:
        | 'Share'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/share/media/[id].vue': {
      routes:
        | 'MediaDetail'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/todos/index.vue': {
      routes:
        | 'Todos'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
