server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # PWA service worker 缓存策略
    location /sw.js {
        add_header Cache-Control "no-cache";
    }
}
